"""Centralized configuration constants for CCP PDF generation."""

# Page dimensions (A4)
PAGE_WIDTH_MM = 210
PAGE_HEIGHT_MM = 297
MARGIN_LEFT_MM = 10
MARGIN_RIGHT_MM = 10
MARGIN_TOP_MM = 10
MARGIN_BOTTOM_MM = 10
USABLE_WIDTH_MM = PAGE_WIDTH_MM - MARGIN_LEFT_MM - MARGIN_RIGHT_MM

# Font
FONT_NAME = "Courier"
FONT_SIZE_PT = 9.5
LINE_SPACING_FACTOR = 1.4
LINE_HEIGHT_MM = FONT_SIZE_PT * 0.3528 * LINE_SPACING_FACTOR

# CCP text layout
LINE_WIDTH_CHARS = 80
MAX_ITEMS_PER_PAGE = 3

# Barcode (Code 128, top-right of first page)
BARCODE_WIDTH_MM = 55
BARCODE_HEIGHT_MM = 12
BARCODE_X_MM = PAGE_WIDTH_MM - MARGIN_RIGHT_MM - BARCODE_WIDTH_MM
BARCODE_Y_MM = MARGIN_TOP_MM
BARCODE_MODULE_WIDTH = 0.3
BARCODE_MODULE_HEIGHT = 8.0
BARCODE_FONT_SIZE = 8
BARCODE_TEXT_DISTANCE = 2.0
BARCODE_QUIET_ZONE = 2.0
