"""Centralized configuration constants for CCP PDF generation."""

# Page dimensions (A4)
PAGE_WIDTH_MM = 210
PAGE_HEIGHT_MM = 297
MARGIN_LEFT_MM = 10
MARGIN_RIGHT_MM = 10
MARGIN_TOP_MM = 10
MARGIN_BOTTOM_MM = 10
USABLE_WIDTH_MM = PAGE_WIDTH_MM - MARGIN_LEFT_MM - MARGIN_RIGHT_MM

# Font — spec requires Courier at 12 CPI (= 10pt)
FONT_NAME = "Courier"
FONT_SIZE_PT = 10.0
LINE_SPACING_FACTOR = 1.4
LINE_HEIGHT_MM = FONT_SIZE_PT * 0.3528 * LINE_SPACING_FACTOR

# CCP text layout
LINE_WIDTH_CHARS = 80
MAX_ITEMS_PER_PAGE = 3

# Barcode — spec requires Code 39, 1.5"-3.1" length, 0.45"-0.55" height, 3:1 ratio
BARCODE_TYPE = "code39"
BARCODE_WIDTH_MM = 63  # ~2.5 inches (within 1.5"-3.1" spec)
BARCODE_HEIGHT_MM = 13  # ~0.5 inch (within 0.45"-0.55" spec)
BARCODE_X_MM = PAGE_WIDTH_MM - MARGIN_RIGHT_MM - BARCODE_WIDTH_MM
BARCODE_Y_MM = MARGIN_TOP_MM
BARCODE_MODULE_WIDTH = 0.4
BARCODE_MODULE_HEIGHT = 11.0  # bar height in mm (~0.5 inch)
BARCODE_FONT_SIZE = 9
BARCODE_TEXT_DISTANCE = 2.0
BARCODE_QUIET_ZONE = 3.0
